### ISSUE TITLE
Pypi stable release

### ISSUE THREAD

**Issue by nim65s** [iplweb/django-autoslug-iplweb#2]
Hi,

Could we have another release without the `.dev0` ?

It's a pain (and not a good practise) to ask pip to include pre-release and development versions with `--pre`in every project x)

**Comment by mpasternak** [comment]
Sure, thanks for filling the issue, I’ll handle this

**Comment by mpasternak** [comment]
Uploaded to PyPI. Please test and reopen if any problems. I also set up TravisCI, https://travis-ci.org/iplweb/django-autoslug-iplweb/
